### ISSUE TITLE
Scroll bar cover buttons

### ISSUE THREAD

**Issue by seescho** [ilia3101/MLV-App#41]
MLV-App Standard style:
The scroll bar covers the very right part of the expanded tabs. darkstyle is OK.

**Comment by masc4ii** [comment]
Really? In my Ubuntu it looks good...
![pic](https://image.ibb.co/mbGriG/Bildschirmfoto.png)

**Comment by masc4ii** [comment]
May it depend on the system style or font size?

**Comment by seescho** [comment]
Lokks like this

https://seescho.files.wordpress.com/2017/10/screenshot_20171102_172509.jpg

**Comment by masc4ii** [comment]
Not nice, I agree. Looks like the fonts are to big. But we fixed the size. So it may be the font type. If this one is to wide, the space may be not enough. But on the other side - also for DarkStyle we don't adjust the font type. So why DarkStyle is okay and Standard is not?!
Does this also happen, if you change the Linux Style or Fonts?

**Comment by seescho** [comment]
Not sure, where I have to change what to answer your question, sorry.

**Comment by masc4ii** [comment]
Can't tell you how exactly you can do that. On Ubuntu there are many possiblilties to adjust really everything - fonts, font sizes, themes, etc...

**Comment by seescho** [comment]
The only effect in taking a smaller font size was a smaller font size. The problem remained. So I played a bit with MainWindow.ui.

I changed minimumSize (Breite) in both, docWidgetEdit and docWidgetContents to 240 and compiled that stuff. Now it looks fine for me.

**Comment by bouncyball-git** [comment]
Now It looks good in light/standard style or it look nice in both light and dark?

**Comment by masc4ii** [comment]
I'll do something what only affects Linux Standardstyle ;-)

**Comment by masc4ii** [comment]
Could you test please?

**Comment by seescho** [comment]
Yes, the cover problem is fixed for me.

It´s interesting, that this change didn´t affect the darkstyle at all. Darkstyle looks like before the change (was OK before and is OK now).

There is one more thing, I noticed:

Darkstyle:
Details: sharpen and Chroma blur radius.
The "0" doesn´t fit fully into the slider fields. I can only see a half "0".

the change fixed that for standard style. In darkstyle the problem remains: a half-cutted "0".

**Comment by masc4ii** [comment]
Yes, that was intended to only change the bahaviour for Linux standard. On Win/OSX Darkstyle/Standard it was okay. 

The "0" is half cutted also by the scrollbar? So for you it looks different than in [this Video](http://nic.caucasus.net/mlvapp/?dir=&download=GL_Draw.mp4) from Bouncyball? Very strange again.

**Comment by masc4ii** [comment]
One Parameter was slightly different for the sliders, which are aligned with the values. I changed that now. Could you please try?

**Comment by seescho** [comment]
No succes. Her a comparition between the two styles (in openSUSE Thunderbold)

![pic](https://seescho.files.wordpress.com/2017/10/screenshot.jpg)

For my taste, darkstyle with it´s smaller buttons looks better than standard style

**Comment by masc4ii** [comment]
Agree, but that depends on the system style. What looks strange for my taste: the fonts are soooo big on your pictures. I think "Chroma Separation (...)" makes this error. If you delete (YCbCr) it could be right - this is too long. When that works, I will delete "(YCbCr)".

**Comment by seescho** [comment]
Standard font on  my system is Noto Sans 10.

**Comment by seescho** [comment]
I deleated (YCbCr).  No change with the error. 
But I noticed another strong behavior, which (maybe) is related to this error. I will do some tests tomorrow and report then.

**Comment by masc4ii** [comment]
Okay... I commited this for you to test too. Hmmmmm, very stange.

**Comment by seescho** [comment]
The "#ifdef ... #elif definied " doesn´t run as expected. I changes MainWindow.cpp lines 758 ff. like this:
```
#ifdef Q_OS_MACX
    if( m_styleSelection == 1 )
        CDarkStyle::assign();
    else
        ui->scrollArea->setVerticalScrollBarPolicy( Qt::ScrollBarAsNeeded );
#endif

#ifdef Q_OS_LINUX
    ui->dockWidgetEdit->setMinimumWidth( 240 );
    ui->dockWidgetContents->setMinimumWidth( 240 );

    if( m_styleSelection == 1 )
        CDarkStyle::assign();
#endif

Now the issue is fixed for me.
I hope, I wrote the code in a correct style. I´m just at page 200 of 1200 in my C++ learnig book :)
```

**Comment by seescho** [comment]
This one should run:

```
#ifdef Q_OS_LINUX
    ui->dockWidgetEdit->setMinimumWidth( 240 );
    ui->dockWidgetContents->setMinimumWidth( 240 );
#endif

    if( m_styleSelection == 1 )
        CDarkStyle::assign();
    else
        ui->scrollArea->setVerticalScrollBarPolicy( Qt::ScrollBarAsNeeded );
```

That´s because I need the minimumWidth (240) in both, standardstyle and darkstyle. Then the problems are fixed in both styles here in openSUSE. I hope, this runs in Ubuntu as well?

What is this line for?:
`ui->scrollArea->setVerticalScrollBarPolicy( Qt::ScrollBarAsNeeded );`
Commenting it out makes no difference for me.

**Comment by seescho** [comment]
Wait. It was late yesterday night.
I guess, this one will not run on windows.

**Comment by masc4ii** [comment]
This could solve it for your Linux:
```
if( m_styleSelection == 1 ) CDarkStyle::assign();
#ifdef Q_OS_MACX
    else ui->scrollArea->setVerticalScrollBarPolicy( Qt::ScrollBarAsNeeded );
#endif
#ifdef Q_OS_LINUX
    ui->dockWidgetEdit->setMinimumWidth( 240 );
    ui->dockWidgetContents->setMinimumWidth( 240 );
#endif
```
But then, on all Linux the sidebar has a bigger width. And if someone comes with a Linux with another font, the problem will be back.

```
#ifdef Q_OS_MACX
    else ui->scrollArea->setVerticalScrollBarPolicy( Qt::ScrollBarAsNeeded );
#endif
```
This line was for OSX only. OSX can have scrollbars which hide when not used. This would crash the design if so, without this line.

**Comment by seescho** [comment]
> This could solve it for your Linux:

Works like a charm. Thank You.

> And if someone comes with a Linux with another font, the problem will be back.

My system default font is Noto Sans 10. I give it a try with noto Sans 14, which is really big. Looks a bit ugly, but no problems with the sidebar.

> This line was for OSX only.

Ahh, I see. I tried it in openSUSE and it worked too. But I prefer, not to hide the scrollbar.

**Comment by masc4ii** [comment]
Okay, then we let it like that for Linux. When it works, all is fine! ;-)
